FROM node:lts-alpine

EXPOSE 8000

RUN mkdir -p /home/node/app && \
    apk add --update --no-cache git openssh

WORKDIR /home/node/app

COPY ./package.json .
RUN yarn cache clean --all && \
    yarn

COPY . .

ENV BRANCH = "master"

CMD ["sh", "-c", "git fetch && git checkout $BRANCH -f && git pull --ff-only && yarn && node"]
