FROM node:lts-alpine

EXPOSE 8000

RUN mkdir -p /home/node/app && \
    apk add --update --no-cache git openssh

WORKDIR /home/node/app

COPY package.json package-lock.json yarn.lock ./
RUN yarn --frozen-lockfile --registry=http://registry.npmmirror.com

COPY . .

ENV BRANCH = "master"

CMD ["sh", "-c", "git fetch && git checkout $BRANCH -f && git pull --ff-only && yarn && node"]
